# Generated by Django 3.1.6 on 2021-03-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolp1', '0002_auto_20210313_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_id',
            new_name='userid',
        ),
    ]
