# Generated by Django 3.1.1 on 2021-03-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolp1', '0005_auto_20210313_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='username',
            new_name='userid',
        ),
    ]
