# Generated by Django 3.1.1 on 2021-03-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolp1', '0011_auto_20210315_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='PhotoFileName',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
