# Generated by Django 3.0.3 on 2021-03-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolp1', '0013_auto_20210316_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='profile_pic',
        ),
    ]
